apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres-label
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
