apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-label
spec:
  type: ClusterIP
  selector:
    app: postgres-label
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
