apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-mdas-base
spec:
  title: Starter Workshop
  description: Starter workshop for Educates
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/lab-mdas-base-files:latest
      includePaths:
      - /workshop/**
      - /templates/**
      - /README.md
    packages:
    - name: postgres-12
      files:
      - image:
          url: ghcr.io/morgan-iverson/mdas-packages/postgres-12:latest
    - name: homebrew
      files:
      - image:
          url: ghcr.io/morgan-iverson/mdas-packages/homebrew:latest
    # - name: gemfire
    #   files:
    #   - image:
    #       url: ghcr.io/morgan-iverson/mdas-packages/gemfire:latest
  session:
    namespaces:
      budget: medium
    applications:
      vcluster:
        enabled: true
      terminal:
        enabled: true
      console:
        enabled: true
      editor:
        enabled: true
    # dashboards: 
    # - name: Gemfire
    #   url: terminal:gemfire
    # objects:
    #   - apiVersion: v1
    #     kind: LimitRange
    #     metadata:
    #       name: resource-limits
    #     spec:
    #       limits:
    #         - type: PersistentVolumeClaim
    #           max:
    #             storage: 10Gi