apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-mdas-base
spec:
  title: Starter Workshop
  description: Starter workshop for Educates
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/lab-mdas-base-files:latest
      includePaths:
      - /workshop/**
      - /templates/**
      - /project/**
      - /spring-modern-data-architecture/**
      - /README.md
    packages:
    - name: postgres-12
      files:
      - image:
          url: ghcr.io/morgan-iverson/mdas-packages/postgres-12:latest
    - name: rabbitmq-in-docker
      files:
      - image:
          url: ghcr.io/morgan-iverson/mdas-packages/rabbitmq-in-docker:latest
    - name: gemfire
      files:
      - image:
          url: ghcr.io/morgan-iverson/mdas-packages/gemfire:latest
  session:
    ingresses:
    - name: rabbitmq
      port: 15672
    namespaces:
      budget: medium
    applications:
      docker:
        enabled: true
      terminal:
        enabled: true
      console:
        enabled: false
      editor:
        enabled: true
    dashboards: 
    - name: RabbitMQ
      url: http://rabbitmq-$(session_namespace).$(ingress_domain)
    - name: Gemfire
      url: terminal:gemfire